database:
  url: ${DATABASE_MYSQL_URL:jdbc:mysql://localhost:3306/sysm_adm_videos_sbx?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true}
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}

amqp:
  admin_auto-create: ${AMQP_ADMIN_AUTO_CREATE:true}
  host: ${AMQP_RABBIT_HOST:localhost}
  port: ${AMQP_RABBIT_PORT:5672}
  username: ${AMQP_RABBIT_USERNAME:adm_videos}
  password: ${AMQP_RABBIT_PASSWORD:123456}

keycloak:
  realm: ${KEYCLOAK_REALM:sysm-codeflix}
  host: ${KEYCLOAK_HOST:http://localhost:8443}

spring:
  server_port: 8080
  undertow_threads_worker: 32
  undertow_threads_io: 2
  flyway_enable: true
  jpa_show_sql: true
  jpa_hibernate_ddl_auto: none