amqp:
  host: ${AMQP_RABBIT_HOST:localhost}
  port: ${AMQP_RABBIT_PORT:5672}
  username: ${AMQP_RABBIT_USERNAME:adm_videos}
  password: ${AMQP_RABBIT_PASSWORD:123456}

mysql:
  url: ${DATABASE_MYSQL_URL:jdbc:mysql://localhost:3306/adm_videos_prod?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8?createDatabaseIfNotExist=true}
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none