database:
  url: jdbc:h2:mem://sysm_adm_videos:MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  username: root
  password: 123456

amqp:
  admin_auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

keycloak:
  realm: test
  host: http://test:8443

logging:
  root: INFO

spring:
  server_port: 8080
  undertow_threads_worker: 32
  undertow_threads_io: 2
  flyway_enable: true
  jpa_show_sql: false
  jpa_hibernate_ddl_auto: none

  #Spring variables changed only for this profile
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
      path: /h2