database:
  url: jdbc:mysql://localhost:3307/sysm_adm_videos_dev?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
  username: root
  password: 123456

amqp:
  admin_auto-create: true
  host: localhost
  port: 5673
  username: adm_videos
  password: 123456

keycloak:
  realm: sysm-codeflix
  host: http://localhost:8444

spring:
  server_port: 8084
  undertow_threads_worker: 32
  undertow_threads_io: 2
  flyway_enable: true
  jpa_show_sql: true
  jpa_hibernate_ddl_auto: none
