mysql:
  url: jdbc:mysql://localhost:3306/adm_videos_dev?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
  username: root
  password: 123456

server:
  port: 8080
  undertow:
    threads:
      worker: 32
      io: 2