version: '3.7'

services:
  app:
    container_name: adm_videos_app
    #build: .
    image: wbaneto/sysm-admin-catalogo-de-videos-java:master-1
    profiles: [ "app" ]
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - adm_videos_network


  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
#    profiles: [ "infra" ]
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_videos_network


  rabbitmq:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3-management
#    profiles: [ "infra" ]
    environment:
        - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
        - RABBITMQ_DEFAULT_USER=adm_videos
        - RABBITMQ_DEFAULT_PASS=123456
        - RABBITMQ_DEFAULT_VHOST=/
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - adm_videos_network

networks:
  adm_videos_network:


# docker compose up -d
# docker-compose --profile infra down
# docker-compose logs --profile infra -f

# docker compose --profile app up -d
# docker-compose --profile app down
# docker-compose logs -f app
